### ISSUE TITLE
Dashboard shows that Application subscribed to topic, even if it's still pending.

### ISSUE THREAD

**Issue by ueberschaersilas-hg** [HermesGermany/galapagos#151]
In the dashboard the message for subscription doesn't change for pending or accepting. And it doesn't get displayed at all, if a request got accepted to declined.

**Comment by albrechtflo-hg** [comment]
There is now an error being displayed on Galapagos startup:

`ERROR 11024 --- [       Thread-6] c.h.a.g.c.impl.ChangeDeserizalizer       : Invalid change type found in Changelog data: TOPIC_SCHEMA_VERSION_DELETED`

There is obviously an entry in the ChangeDeserializer missing. Please add.
