### ISSUE TITLE
Changelog "inconsistent" when deleting and re-creating JSON schema

### ISSUE THREAD

**Issue by PolatEmre-hg** [HermesGermany/galapagos#204]
If I'm experimenting with JSON schemas, I might delete versions and create them again. Maybe more often. Apparently, however, the deletion is not recorded in the changelog. This makes it seem like there should be dozens of versions. The  changelog should therefore ideally also log the deletion of a JSON schema.

**Comment by ueberschaersilas-hg** [comment]
Done via #171
