### ISSUE TITLE
Delete Json-Schema with Subscribers using a feature toggle

### ISSUE THREAD

**Issue by PolatEmre-hg** [HermesGermany/galapagos#23]
As Application Topic Owner I want to be able to delete a published Schema Version even if there are subscribers on the respective Topic. This way I am not bound to the Developer Teams and can just delete a Json-Schema If i want to .
Deleting a schema of a Topic with subscribers  should **only** be possible on the DEV-Stage, on all other stages the feature toggle will not be used. Please Note that the schema still must not be deletable if it is already staged to the next environment.
The feature toggle has to be defined in the application.properties file.

**Comment by albrechtflo-hg** [comment]
Merged into next_minor; released with Galapagos 1.8.0.
