### ISSUE TITLE
Configurable Write Access for Developers on some environments

### ISSUE THREAD

**Issue by albrechtflo-hg** [HermesGermany/galapagos#248]
As a Galapagos Administrator, I want to enable Developers to get write access to some clusters using their Developer Authentications, so they can e.g. insert test data into topics of their applications. But on production, they shall e.g. only be able to read the data for error analysis.

Suggestion is a "developerWriteAccess" flag per configured Kafka environment, which is by default false for backward compatibility.

**Comment by ueberschaersilas-hg** [comment]
Done via #249
