### ISSUE TITLE
Upgrade to Spring Boot 3

### ISSUE THREAD

**Issue by jimbethancourt** [HermesGermany/galapagos#292]
I've figured out how to get OpenRewrite migration recipes working and have run the Spring Boot 2.7 --> Spring Boot 3 recipe on the next_version branch and thought it would be a great way to try something big by running it on Galapagos.

Unfortunately Keycloak has been deprecated and I'm not familiar with implementing Spring Security's OAuth 2 authentication, so this will need to be addressed since I have commented out the SecurityConfig class at this time.  It would likely make the most sense to create a separate branch for this work to be done on the galapagos repository before merging into main.  

Can one of the Galapagos maintainers update the SecurityConfig class to use Spring Security OAuth 2?

**Comment by albrechtflo-hg** [comment]
As we already merged this, but somehow this issue did not get auto-closed, I will close it now.
