### ISSUE TITLE
Generate API Keys for Confluent Cloud Support

### ISSUE THREAD

**Issue by PolatEmre-hg** [HermesGermany/galapagos#60]
As part of the support of Confluent Cloud, we will have to generate API keys from Galapagos. Since there is currently no officially available API for creating and deleting API keys, we have to use a command line client and "wrap" with Java - or use the "unofficial" API that the command line client uses.

**Comment by albrechtflo-hg** [comment]
Confluent Cloud Integration Topics are handled via another channel for now.
